name = "TuringStars"
uuid = "95955baf-4ac1-410e-9061-95296ea9737c"
authors = ["Batmaev <vbbatmaev@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
